version: '3'
services:
  main:
    user: 
      docker

    build: 
      context: .
      dockerfile: Dockerfile
    
    network_mode: "host"

    volumes:
      - ..:/src

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"  
